<a href="https://colab.research.google.com/github/FarrazNouval/ml_zoomcamp/blob/main/ml_zoomcamp_hw_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Question 1: What's the version of NumPy that you installed?

In [ ]:
import numpy as np

In [ ]:
print(np.__version__)

1.21.6


getting the data

In [ ]:
!wget https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-02-car-price/data.csv

--2022-09-08 11:59:06--  https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-02-car-price/data.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.109.133, 185.199.110.133, 185.199.108.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.109.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1475504 (1.4M) [text/plain]
Saving to: ‘data.csv.2’

data.csv.2          100%[===================>]   1.41M  --.-KB/s    in 0.05s   

2022-09-08 11:59:07 (25.8 MB/s) - ‘data.csv.2’ saved [1475504/1475504]



Question 2: How many records are in the dataset?

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('/content/data.csv')
df.head()

Make       Model  Year             Engine Fuel Type  Engine HP  \
0  BMW  1 Series M  2011  premium unleaded (required)      335.0   
1  BMW    1 Series  2011  premium unleaded (required)      300.0   
2  BMW    1 Series  2011  premium unleaded (required)      300.0   
3  BMW    1 Series  2011  premium unleaded (required)      230.0   
4  BMW    1 Series  2011  premium unleaded (required)      230.0   

   Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
0               6.0            MANUAL  rear wheel drive              2.0   
1               6.0            MANUAL  rear wheel drive              2.0   
2               6.0            MANUAL  rear wheel drive              2.0   
3               6.0            MANUAL  rear wheel drive              2.0   
4               6.0            MANUAL  rear wheel drive              2.0   

                         Market Category Vehicle Size Vehicle Style  \
0  Factory Tuner,Luxury,High-Performance      Compact         Coupe   
1                     Luxury,Performance      Compact   Convertible   
2                Luxury,High-Performance      Compact         Coupe   
3                     Luxury,Performance      Compact         Coupe   
4                                 Luxury      Compact   Convertible   

   highway MPG  city mpg  Popularity   MSRP  
0           26        19        3916  46135  
1           28        19        3916  40650  
2           28        20        3916  36350  
3           28        18        3916  29450  
4           28        18        3916  34500

In [ ]:
print('the records in dataset is {}'.format(df.shape[0]))


the records in dataset is 11914


Question 3: Who are the most frequent car manufacturers (top-3) according to the dataset?

In [ ]:
producers = df['Make'].value_counts(ascending=False)
producers[:3]

Chevrolet     1123
Ford           881
Volkswagen     809
Name: Make, dtype: int64

Question 4: What's the number of unique Audi car models in the dataset?

In [ ]:
audi = df[df['Make'] == 'Audi']
audi['Model'].nunique()

34

Question 5: How many columns in the dataset have missing values?

In [ ]:
df.isna().sum()

Make                    0
Model                   0
Year                    0
Engine Fuel Type        3
Engine HP              69
Engine Cylinders       30
Transmission Type       0
Driven_Wheels           0
Number of Doors         6
Market Category      3742
Vehicle Size            0
Vehicle Style           0
highway MPG             0
city mpg                0
Popularity              0
MSRP                    0
dtype: int64

> * Find the median value of "Engine Cylinders" column in the dataset.
* Next, calculate the most frequent value of the same "Engine Cylinders".
* Use the fillna method to fill the missing values in "Engine Cylinders" with the most frequent value from the previous step.
* Now, calculate the median value of "Engine Cylinders" once again.

In [ ]:
ec = df['Engine Cylinders']
median_1 = ec.median()
mode_1 = ec.mode()
ec.fillna(mode_1, inplace=False)
median_2 = ec.median()

In [ ]:
print('median before fillna = {}'.format(median_1))
print('median after fillna = {}'.format(median_2))
if median_1 == median_2:
  print("the median after fillna is same as before.")
else:
  print("the median changes.")

median before fillna = 6.0
median after fillna = 6.0
the median after fillna is same as before.


Question 7:
> * Select all the "Lotus" cars from the dataset.
*Select only columns "Engine HP", "Engine Cylinders".
* Now drop all duplicated rows using drop_duplicates method (you should get a dataframe with 9 rows).
* Get the underlying NumPy array. Let's call it X.
* Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.
* Invert XTX.
* Create an array y with values [1100, 800, 750, 850, 1300, 1000, 1000, 1300, 800].
* Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.
* What's the value of the first element of w?

In [56]:
lotus = df[df['Make'] == 'Lotus']
lotus = lotus[['Engine HP', 'Engine Cylinders']]
lotus = lotus.drop_duplicates()
lotus


Engine HP  Engine Cylinders
3912      189.0               4.0
3913      218.0               4.0
3918      217.0               4.0
4216      350.0               8.0
4257      400.0               6.0
4259      276.0               6.0
4262      345.0               6.0
4292      257.0               4.0
4293      240.0               4.0

In [119]:
X = lotus.values
print(X)

[[189.   4.]
 [218.   4.]
 [217.   4.]
 [350.   8.]
 [400.   6.]
 [276.   6.]
 [345.   6.]
 [257.   4.]
 [240.   4.]]


In [121]:
XTX = np.matmul(X.T, X)
XTX = XTX.astype('int')
XTX

array([[731684,  13410],
       [ 13410,    252]])

In [122]:
XTX_inv = np.linalg.inv(XTX)

In [123]:
XTX_inv

array([[ 5.53084235e-05, -2.94319825e-03],
       [-2.94319825e-03,  1.60588447e-01]])

In [124]:
y = np.array([1100, 800, 750, 850, 1300, 1000, 1000, 1300, 800])
w = XTX_inv.dot(X.T).dot(y)

In [125]:
w[0]

4.594944810094551